name: Sheet to Json Workflow

on:
  schedule:
    # every 60 minutes the job will run
    - cron: "0 */4 * * *"
  push:
    branches:
      - master

jobs:
  update-json-data:
    runs-on: ubuntu-latest
    timeout-minutes: 9

    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
  
      - name: Install Dependencies
        run: npm install

      - name: Run
        run: npm start
        env:
          SHEET_ID_2: ${{ secrets.SHEET_ID_2 }}
     
      - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          