name: Sheet to JSON

on:
  schedule:
    # every 60 minutes the job will run
    - cron: "0 */4 * * *"
  push:
    branches:
      - master
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-json-data:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Create local changes
      run: |
        npm install
        npm start
      env:
        SHEET_ID_2: ${{ secrets.SHEET_ID_2 }}
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "update json" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
